### PR TITLE
Update rendering settings for emrbyo1 images

### PR DESCRIPTION
**Pull request by dominikl**
See PR title.

### CODE REVIEW

**Comment by sbesson** [comment]
:+1: Has this been deployed on `test60`?

**Comment by dominikl** [comment]
It doesn't work unfortunately, doesn't set start/end. Have to try with yml files again instead of json.

**Comment by dominikl** [comment]
Ok, there's no point in setting the rendering settings on idr-testing. It has to be done manually anyway. Export and import rendering settings with render plug doesn't work, it ignores start and end values:
```
...
Set rendering settings for SPM00_TM000512_CM00_CM01_CHN01_xzProjection.klb
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
0:active=True,color=00FF00,label=H2B-eGFP,min=0.0,start=None,end=None,max=65535.0
1:active=True,color=FF0000,label= myr-tdTomato,min=0.0,start=None,end=None,max=65535.0
greyscale=False
...
```

**Comment by dominikl** [comment]
But I guess I can put the exported rendering settings into the repository, just for reference, in that case this PR would still make sense.

**Comment by dominikl** [comment]
The issue with the rendering settings is this: If you adjust the rendering settings manually in web, this sets the 'start' and 'end' values (I assume that's expected). These values are correctly exported by the render plugin. But they aren't picked up by the 'render set' command, instead the min/max values are used as start/end. Must be a bug in the render plugin.

**Comment by sbesson** [comment]
A few yaml lint errors reported in `experimentA/idr0044-experimentA-bulkmap-config.yml` and the various rendering configuration files.

**Pull request merged**
